name: "Publish Prebuilt"
author: "Keren Dong"
description: "Publish Prebuilt to AWS S3"
inputs:
  token:
    description: "GitHub token"
  expore-in:
    required: true
    description: 'Human readable expire duration'
runs:
  using: "node12"
  main: "dist/index.js"
