name: "Purge Artifacts"
author: "Keren Dong"
description: "Purge expired GitHub artifacts"
inputs:
  token:
    description: "GitHub token"
  expire-in:
    required: true
    description: 'Human readable expire duration'
  only-prefix:
    required: false
    description: 'Only artifacts with the specified prefix will be deleted'
    default: ''
  except-prefix:
    required: false
    description: 'Artifacts with this prefix will not be included for deletion'
    default: ''
runs:
  using: "node16"
  main: "dist/index.js"
